# Generated by Django 5.2.4 on 2025-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponibilidade', models.IntegerField()),
                ('intensidade', models.IntegerField()),
                ('nota_geral', models.IntegerField()),
                ('opiniao', models.TextField()),
            ],
        ),
    ]
